name: "Walshification"
description: "My programming blog."
avatar: https://avatars0.githubusercontent.com/u/5120876?v=2&s=460

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments